---
# SPDX-FileCopyrightText: Jürgen Mülbert
#
# SPDX-License-Identifier: MIT
#
name: 'Pull Request Actions'

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

permissions:
  contents: read

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
  
  auto-approve:
     runs-on: ubuntu-latest
     permissions:
       pull-requests: write
     steps:
      - uses: hmarr/auto-approve-action@v4
        if: github.actor == 'dependabot[bot]'
        with:
          github-token: ${{ secrets.token }} 

  lint-pr-title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          github-token: ${{ secrets.token }} 
